### ISSUE TITLE
Unable to use cloned stream as normal ReadableStream

### ISSUE THREAD

**Issue by ghost** [mcollina/cloneable-readable#46]
Hi, I'm using this library in order to upload a stream to different destination, one of this is an AWS S3 cloud storage provider. The library I'm using (https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-lib-storage/) does need a `Readable` as the payload of the upload, but since the clone has not the Readable prototype I can't use this with that library. Any suggestion?

I get specifically this error:
`Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob`

**Comment by ghost** [comment]
I'm tempted to use `Object.setPrototypeOf(clone, Readable.prototype)` but not knowing how the library operates under the hood I've no idea if something may go wrong.

**Comment by mcollina** [comment]
Can you include a full stacktrace? Is that a TS error or a JS one?

**Comment by ghost** [comment]
```
      "type": "Error",
      "message": "Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob;.",
      "stack":
          Error: Body Data is unsupported format, expected data to be one of: string | Uint8Array | Buffer | Readable | ReadableStream | Blob;.
              at getChunk (/usr/src/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:166:9)
              at _Upload.__doMultipartUpload (/usr/src/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:374:24)
              at _Upload.done (/usr/src/app/node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:203:37)
              at S3Driver.putObject (/usr/src/app/plugins/storage/drivers/S3.js:110:18)
              at /usr/src/app/plugins/hrt/HRTStorage.js:108:37
              at Array.map (<anonymous>)
              at HRTStorage.putHRT (/usr/src/app/plugins/hrt/HRTStorage.js:108:21)
              at Object.upload (/usr/src/app/plugins/hrt/upload.js:51:18)
              at Object.<anonymous> (/usr/src/app/routes/hrts/index.js:86:29)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

That's a runtime error

**Comment by ghost** [comment]
Out of curiosity, I just tried by forcing the `Readable` prototype but I get this other error:

```
TypeError: dest.write is not a function

      at Cloneable.ondata (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/readable.js:705:22)
      at addChunk (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/readable.js:321:12)
      at readableAddChunk (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/readable.js:298:9)
      at Cloneable.Object.<anonymous>.Readable.push (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/readable.js:244:10)
      at node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/transform.js:159:12
      at Cloneable.Object.<anonymous>.PassThrough._transform (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/passthrough.js:38:3)
      at Cloneable.Object.<anonymous>.Transform._write (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/transform.js:153:8)
      at writeOrBuffer (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
      at _write (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
      at Cloneable.Object.<anonymous>.Writable.write (node_modules/cloneable-readable/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
```

It may not be the right solution

**Comment by mcollina** [comment]
For some
obscure reason aws-sdk does not support readable-stream and it relies on an instanceof check at https://github.com/aws/aws-sdk-js-v3/blob/1cc4de91fb080b32d58c5b45e0debac42a45f99e/lib/lib-storage/src/chunker.ts#L17.

Considering how popular readable-stream is, we might want to ask for a fix there.

(The solution would be to stop using readable-stream here and just use stream. However that would 100% increase the maintenance burden on this module).

**Comment by ghost** [comment]
So, to clarify, in this case we have two options:

1. Ask aws/lib-storage to support [readable-stream](https://www.npmjs.com/package/readable-stream) for the uploads
2. Migrate [cloneable-readable](https://github.com/mcollina/cloneable-readable) to `node:stream` and do not rely on `readable-stream` anymore? With the maintainance problem..

Is this right?
Is there any way to wrap `readable-stream` in order to ensure compatibility with `stream`?

**Comment by mcollina** [comment]
Yes, you pipeline it to a PassThrough, and then use that stream.

**Comment by ghost** [comment]
Thank you @mcollina, so `const stream = clone.pipe(new PassThrough())` is enough or I should add some error handling logic?

**Comment by mcollina** [comment]
`const stream = pipeline(clone, new PassThrough(), () => {})` would do.

**Comment by florianbepunkt** [comment]
@mcollina Since the native stream implementation matured quite a bit over the past few years, why not switch to native streams? Is there any upside to use readable-stream?

**Comment by mcollina** [comment]
Mostly time on my end. It's usually better spent doing other stuff, this works fine.
