### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by eran-nussbaum** [mcollina/cloneable-readable#7]
hello,
since version 1.1.0 published 27 minutes ago my npm v2.15.8 started having this error:
```
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/node_modules/gulp-rev-collector/node_modules/vinyl/node_modules/cloneable-readable/index.js:3:19)
```
which points [here](https://github.com/mcollina/cloneable-readable/blob/master/index.js#L3)

I'd appreciate your help.

Thanks,
Eran

**Comment by mcollina** [comment]
My bad, fixed in 1.1.1.

**Comment by eran-nussbaum** [comment]
Thanks for the quick response and fix.
I approve the fix works for me.

**Comment by mcollina** [comment]
No worries!
